shellcheck docker-enable

diff --git a/dotfiles/bin/docker-enable b/dotfiles/bin/docker-enable
--- a/dotfiles/bin/docker-enable
+++ b/dotfiles/bin/docker-enable
@@ -5,46 +5,46 @@
 
 
 function printUsage {
-    echo -e "\ndocker-enable: enable or disable docker (including autostart)";
-    echo "Usage: docker-enable [on|yes]|[off|no]";
+    echo -e "\ndocker-enable: enable or disable docker (including autostart)"
+    echo "Usage: docker-enable [on|yes]|[off|no]"
 }
 
-if [ "$#" != "1" ];
+if [ "$#" != "1" ]
 then
     echo "Invalid number of args"
-    printUsage;
-    exit 1;
+    printUsage
+    exit 1
 fi
 
-if [ $(which docker) ];
+if command -v docker
 then
-    if [ $1 = "on" ] || [ $1 = "yes" ];
+    if [ "$1" = "on" ] || [ "$1" = "yes" ]
     then
-        echo "Enabling docker";
+        echo "Enabling docker"
         sudo systemctl start docker.service
-        sudo systemctl enable docker.service;
+        sudo systemctl enable docker.service
         sudo systemctl start docker.socket
-        sudo systemctl enable docker.socket;
-        sudo chmod 666 /var/run/docker.sock;
+        sudo systemctl enable docker.socket
+        sudo chmod 666 /var/run/docker.sock
         sudo systemctl start containerd.service
-        sudo systemctl enable containerd.service;
+        sudo systemctl enable containerd.service
         echo "Done"
-    elif [ $1 = "off" ] || [ $1 = "no" ];
+    elif [ "$1" = "off" ] || [ "$1" = "no" ]
     then
-        echo "Disabling docker";
+        echo "Disabling docker"
         sudo systemctl stop docker.service
-        sudo systemctl disable docker.service;
+        sudo systemctl disable docker.service
         sudo systemctl stop docker.socket
-        sudo systemctl disable docker.socket;
+        sudo systemctl disable docker.socket
         sudo systemctl stop containerd.service
-        sudo systemctl disable containerd.service;
+        sudo systemctl disable containerd.service
         echo "Done"
     else
-        echo "Invalid argument: $1";
-        printUsage;
-        exit 1;
+        echo "Invalid argument: $1"
+        printUsage
+        exit 1
     fi
 else
-    echo "docker not installed";
-    exit 2;
+    echo "docker not installed"
+    exit 2
 fi
